# cloudbuild.yaml

substitutions:
  _GCE_ZONE: 'us-central1'
  _GCP_PROJECT_ID: 'cool-ruler-461702-p8'
  # _GCS_BUCKET_NAME is not needed for this simplified test
  # _UNITY_EDITOR_VERSION is not needed for this simplified test
  # _UNITY_PROJECT_NAME is not needed for this simplified test
  # _UNITY_USERNAME is not needed for this simplified test

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Test SSH Connection Only'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # This command uses the Cloud Build substitution for zone.
    # The inner command "echo 'Hello from GCE!'" contains no '$' symbols.
    gcloud compute ssh unity-build-machine-windows --zone=${_GCE_ZONE} --command="echo 'Hello from GCE! This is a test.'"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_GCE_ZONE}'
  - 'CLOUDSDK_CORE_PROJECT=${_GCP_PROJECT_ID}'
  # No other env vars needed for this test

# logs_bucket is still required at the top level
logs_bucket: 'gs://my_adk_unity_hackathon_builds_2025/cloudbuild-logs'