# cloudbuild.yaml

substitutions:
  _GCE_ZONE: 'us-central1-b'
  _PROJECT_ID: 'cool-ruler-461702-p8' # Ensure this is your actual Project ID string

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Test SSH Connection Only'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # This command uses the Cloud Build substitution for zone.
    # Add --log-http to get verbose output including API calls.
    gcloud compute ssh unityadmin@unity-build-machine-windows2 \
      --zone=${_GCE_ZONE} \
      --project=${_PROJECT_ID} \
      --log-http \
      --command="echo 'Hello from GCE! This is a test.'"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_GCE_ZONE}'
  - 'CLOUDSDK_CORE_PROJECT=${_PROJECT_ID}'

# logs_bucket is still required at the top level
logs_bucket: 'gs://my_adk_unity_hackathon_builds_2025/cloudbuild-logs'